services:
  dev:
    build: .
    volumes:
      - .:/app
      - deno-cache:/deno-dir
    environment:
      - DENO_DIR=/deno-dir
    ports:
      - "8000:8000"
    command: deno task dev

volumes:
  deno-cache:
