name: Test

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - '**.ts'
      - 'deno.json'
      - 'deno.lock'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.0

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: |
          deno check src/
          deno check tests/

      - name: Run tests
        run: deno test --allow-read

      - name: Cache dependencies
        if: hashFiles('deps.ts') != ''
        run: |
          deno cache --lock=deno.lock deps.ts
