name: Test

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - '**.ts'
      - 'deno.json'
      - 'deno.lock'
      - '.github/workflows/ci.yml'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.0

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check

      - name: Run tests
        run: deno test --allow-read

      - name: Cache dependencies
        run: |
          deno cache main.ts
          deno cache --lock=deno.lock --lock-write deps.ts

  cache:
    name: Cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-
